### PR TITLE
Cc link2008 patch 2

### PR DESCRIPTION
**Pull request by CCLink2008**
修改部分不准确的内容。

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@huacnlee Could you add him as collaborator? It would be the same as what @CCLink2008 is doing now, but it would allow him to help close issues and create branch pull requests instead of forking. :bow:

**Comment by huacnlee** [comment]
Tomorrow morning

**Comment by huacnlee** [comment]
I have invited @CCLink2008.

**Comment by JuanitoFatas** [comment]
> I have invited @CCLink2008.

:+1: 

@CCLink2008 you can push to here instead of forking now, easier to open Pull Request :smile:

**Comment by CCLink2008** [comment]
:blush:

**Pull request merged**
